source("https://bioconductor.org/biocLite.R")
biocLite("affy", "amap", "annotate", "arrayQualityMetrics", "baySeq",
         "Biobase", "BiocParallel", "biomaRt", "Biostrings",
         "BSgenome.Hsapiens.UCSC.hg19", "chipseq", "cqn",
         "cummeRbund", "DESeq", "DESeq2", "DiffBind", "doMC",
         "doParallel", "dplyr", "DSS", "edgeR", "foreach",
         "functional", "genome", "GenomicFeatures", "GenomicRanges",
         "ggdendro", "ggplot2", "GMD", "graphite", "grid", "GSEABase",
         "inline", "magrittr", "MASS", "matchBox", "Matrix",
         "multcomp", "multicore", "mvtnorm", "openxlsx", "optparse",
         "org.Hs.eg.db", "parallel", "partitions", "plyr",
         "RColorBrewer", "reshape", "reshape2", "Rsamtools",
         "rtracklayer", "R.utils", "scales", "ShortRead", "snow",
         "splines", "spp", "sqldf", "statmod", "stringr",
         "TxDb.Hsapiens.UCSC.hg19.knownGene", "xlsx")
